Вправа 1. Вводиться число n. Вивести масив разміра nхn, в якому по
діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [48]:
from timeit import default_timer as timer


def task_1():
    n = int(input("Enter your number"))
    start = timer()
    base_list = []
    for i in range(1, n+1):
        row = []
        for a in range(1, n+1):
            if a != i:
                row.append(0)
            else:
                row.append(i)
        base_list.append(row)
    for r in base_list:
        print(r, end="")
        print()
    end = timer()
    print(f"It took {end - start} seconds")


task_1()



Enter your number10
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 2, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 3, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 4, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 5, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 6, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 7, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 8, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 9, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 10]
It took 0.00011030002497136593 seconds


In [49]:
import time
import numpy as np


def task_1():
    n = int(input("Enter your number"))
    start = time.time()
    base_list = np.zeros([n, n], dtype=int)
    for i in range(0, n):
        base_list[i][i] = i+1
    print(base_list)
    end = time.time()
    print(f"It took {end - start} seconds")


task_1()


Enter your number10
[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]
It took 0.0 seconds


Numpy впорався швидше.

Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в
якому в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші
елементи дорівнюють 1.

In [51]:
from timeit import default_timer as timer


def task_3():
    n = int(input("Enter n: \n"))
    m = int(input("Enter m: \n"))
    r = int(input("Enter r: \n"))
    c = int(input("Enter c: \n"))
    start = timer()
    base_array = []
    zero_string = [0]*m
    ones_string = [1]*m
    for i in range(0, m):
        if i % c == 0:
            ones_string[i] = 0
    for i in range(0, n):
        if i % r == 0:
            base_array.append(zero_string)
        else:
            base_array.append(ones_string)

    for r in base_array:
        print(r, end="")
        print()
    end = timer()
    print(f"It took {end - start} seconds")


task_3()


Enter n: 
4
Enter m: 
10
Enter r: 
2
Enter c: 
3
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0, 1, 1, 0]
It took 0.00033249997068196535 seconds


In [52]:
import time
import numpy as np


def task_3():
    n = int(input("Enter n: \n"))
    m = int(input("Enter m: \n"))
    r = int(input("Enter r: \n"))
    c = int(input("Enter c: \n"))
    start = time.time()
    base_array = np.zeros([n, m], dtype=int)
    for i in range(1, n, r):
        for a in range(1, m):
            if a % c != 0:
                base_array[i][a] = 1
    print(base_array)
    end = time.time()
    print(f"It took {end - start} seconds")


task_3()


Enter n: 
4
Enter m: 
10
Enter r: 
2
Enter c: 
3
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0 1 1 0]]
It took 0.0 seconds


Numpy знов переміг.

Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на -
1.

In [53]:
import time


def task_6():
    base_list = [int(item) for item in input("Enter the numbers: ").split()]
    start = time.time()
    for i in range(0, len(base_list)):
        if base_list[i] != 0:
            base_list[i] = -1
    print(base_list)
    end = time.time()
    print(f"It took {end - start} seconds")


task_6()

Enter the numbers: 3 -12 0 -123 0 0 3213 0 12312312 0 -2 0 0 0 232 -123123 0
[-1, -1, 0, -1, 0, 0, -1, 0, -1, 0, -1, 0, 0, 0, -1, -1, 0]
It took 0.0 seconds


In [54]:
import time
import numpy as np


def task_6():
    base_list = np.array([int(item) for item in input("Enter the numbers: ").split()])
    start = time.time()
    base_list[base_list != 0] = -1
    print(base_list)
    end = time.time()
    print(f"It took {end - start} seconds")


task_6()


Enter the numbers: 3 -12 0 -123 0 0 3213 0 12312312 0 -2 0 0 0 232 -123123 0
[-1 -1  0 -1  0  0 -1  0 -1  0 -1  0  0  0 -1 -1  0]
It took 0.0 seconds


Різницю не видно через занадто малий час виконання але видно що алгоритм numpy менш покладається на цикли, а значить більш швидкий та оптимізований.


Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому кількість
нульових та ненульвих елементів.

In [55]:
import time


def task_8():
    base_list = [int(item) for item in input("Enter the numbers: ").split()]
    start = time.time()
    zero_count = 0
    nonzero_count = 0
    for i in base_list:
        if i == 0:
            zero_count += 1
        else:
            nonzero_count += 1
    print(f"Zeros: {zero_count}")
    print(f"Non-zeros: {nonzero_count}")
    end = time.time()
    print(f"It took {end - start} seconds")


task_8()


Enter the numbers: 0 0 0 3 3 3 4 0 3 0 0 0 3 3 3 4 0 3 0 0 0 3 3 3 4 0 3 0 0 0 3 3 3 4 0 3
Zeros: 16
Non-zeros: 20
It took 0.0 seconds


In [57]:
import time
import numpy as np


def task_8():
    base_list = np.array([int(item) for item in input("Enter the numbers: ").split()])
    start = time.time()

    print(f"Zeros: {len(base_list) - np.count_nonzero(base_list)}")
    print(f"Non-zeros: {np.count_nonzero(base_list)}")
    end = time.time()
    print(f"It took {end - start} seconds")


task_8()


Enter the numbers: 0 0 0 3 3 3 4 0 3 0 0 0 3 3 3 4 0 3 0 0 0 3 3 3 4 0 3 0 0 0 3 3 3 4 0 3
Zeros: 16
Non-zeros: 20
It took 0.0 seconds


Знов, занадто малий час виконання щоб таймер щось засік і не округляв. Але реалізація через numpy все ще зручніша та елегантніша.

Вправа 13. Розмістити на полі 8х8 нулі та одиниці в шахматному порядку,
використовуючи функцію повторення (*).

In [6]:
import time


def task_13():
    start = time.time()
    odd_string = [0, 1] * 4
    even_string = [1, 0] * 4
    base_list = [odd_string, even_string] * 4
    for r in base_list:
        print(r, end="")
        print()
    end = time.time()
    print(f"It took {end - start} seconds")


task_13()


[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
It took 0.0010001659393310547 seconds


In [11]:
import time
import numpy as np


def task_13():
    start = time.time()
    base_row = np.zeros(8, dtype=int)
    base_list = np.array([base_row] * 8)
    base_list[1::2, ::2] = 1
    base_list[::2, 1::2] = 1
    print(base_list)
    end = time.time()
    print(f"It took {end - start} seconds")


task_13()


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
It took 0.0010004043579101562 seconds


Майже однаковий час виконання. Декілька тестувань показали що одне може бути швидше за інше і це випадково, але завдання не дуже зручно для numpy(обов'язково використати *).

Вправа 15. Заповнити парні стовбчики матриці розміром n х n одиницями, а
непарні – нулями.

In [8]:
import time


def task_15():
    n = int(input("Enter n: \n"))
    start = time.time()
    row = [0] * n
    for i in range(0, n):
        if i % 2 == 1:
            row[i] = 1
    base_list = [row] * n
    for r in base_list:
        print(r, end="")
        print()
    end = time.time()
    print(f"It took {end - start} seconds")


task_15()


Enter n: 
10
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
It took 0.0010004043579101562 seconds


In [10]:
import time
import numpy as np


def task_15():
    n = int(input("Enter n: \n"))
    start = time.time()
    base_list = np.zeros((n, n), dtype=int)
    for i in range(0, n):
        for a in range(0, n):
            if a % 2 == 1:
                base_list[i][a] = 1
    print(base_list)
    end = time.time()
    print(f"It took {end - start} seconds")


task_15()


Enter n: 
10
[[0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]]
It took 0.0010001659393310547 seconds


Незначна різниця у швидкості, але numpy у середньому працює швидше. 

Вправа 16. Заповнити вектор значеннями від 0 до n. Всі значення, що більші
за n/4 та менші за 3n/4 замінити нулями

In [19]:
import time


def task_16():
    n = int(input("Enter n: \n"))
    start = time.time()
    base_vector = [*range(0, n+1)]
    for i in range(0, n+1):
        if (base_vector[i] > n/4) and (base_vector[i] < 3*n/4):
            base_vector[i] = 0
    print(base_vector)
    end = time.time()
    print(f"It took {end - start} seconds")


task_16()


Enter n: 
30
[0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 24, 25, 26, 27, 28, 29, 30]
It took 0.0 seconds


In [18]:
import time
import numpy as np


def task_16():
    n = int(input("Enter n: \n"))
    start = time.time()
    base_vector = np.arange(0, n+1)
    for i in range(0, n+1):
        if (base_vector[i] > n / 4) and (base_vector[i] < 3 * n / 4):
            base_vector[i] = 0
    print(base_vector)
    end = time.time()
    print(f"It took {end - start} seconds")


task_16()


Enter n: 
30
[ 0  1  2  3  4  5  6  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 23
 24 25 26 27 28 29 30]
It took 0.0009996891021728516 seconds


Як не дивно, numpy впорався з даним завданням гірше, але це може бути проблема через схожу реалізацію.

Вправа 18. Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99.
Визначити кількість унікальних чисел в послідовності.

In [24]:
import time
import random


def task_18():
    n = int(input("Enter n: \n"))
    start = time.time()
    base_vector = []
    originals = []
    for i in range(0, n):
        base_vector.append(random.randint(0, 99))
        if base_vector[i] not in originals:
            originals.append(base_vector[i])
    print(f"В послідовності {base_vector} - {len(originals)} оригінальних чисел")
    end = time.time()
    print(f"It took {end - start} seconds")


task_18()


Enter n: 
30
В послідовності [52, 83, 70, 87, 73, 79, 23, 17, 87, 83, 37, 72, 48, 8, 55, 72, 24, 78, 4, 76, 20, 25, 65, 99, 41, 75, 19, 6, 12, 40] - 27 оригінальних чисел
It took 0.0 seconds


In [25]:
import time
import numpy as np


def task_18():
    n = int(input("Enter n: \n"))
    start = time.time()
    base_vector = np.random.randint(99, size=n)
    print(f"В послідовності {base_vector} - {len(np.unique(base_vector))} оригінальних чисел")
    end = time.time()
    print(f"It took {end - start} seconds")


task_18()


Enter n: 
30
В послідовності [71 47  4 81 67 22 69 61 57 45 47 94 65 86 15 74 29 19 93 97 61 15 39 10
  7 71 49 41 75 53] - 26 оригінальних чисел
It took 0.0 seconds


Занадто малі значення щоб зрозуміти різницю, але реалізація через numpy коротша та елегантніша.

Вправа 20. Згенерувати вектор із n випадкових елементів, що лежать в
інтервалі (0,1). Замінити максимальний елемент на 0.

In [37]:
import time
import random


def task_20():
    n = int(input("Enter n: \n"))
    start = time.time()
    base_vector = []
    new_vector = []
    biggest = 0
    for i in range(0, n):
        base_vector.append(random.random())
        if base_vector[i] > biggest:
            biggest = base_vector[i]
    for i in range(0, n):
        new_vector.append(base_vector[i])
        if base_vector[i] == biggest:
            new_vector[i] = 0
    print(f"Початковий вектор {base_vector} \nЗмінений вектор {new_vector}")
    end = time.time()
    print(f"It took {end - start} seconds")


task_20()


Enter n: 
5
Початковий вектор [0.26622339005336204, 0.4324155535259988, 0.12468857571305847, 0.7728335892070438, 0.8856347403515291] 
Змінений вектор [0.26622339005336204, 0.4324155535259988, 0.12468857571305847, 0.7728335892070438, 0]
It took 0.0 seconds


In [36]:
import time
import numpy as np


def task_20():
    n = int(input("Enter n: \n"))
    start = time.time()
    base_vector = np.random.uniform(low=0.0, high=1.0, size=n)
    new_vector = np.copy(base_vector)
    new_vector[np.argmax(new_vector)] = 0
    print(f"Початковий вектор {base_vector} \nЗмінений вектор {new_vector}")
    end = time.time()
    print(f"It took {end - start} seconds")


task_20()


Enter n: 
5
Початковий вектор [0.40797207 0.33869694 0.80581879 0.0625032  0.47871612] 
Змінений вектор [0.40797207 0.33869694 0.         0.0625032  0.47871612]
It took 0.00099945068359375 seconds


Знов незначна різниця у швидкості, але рішення через numpy зручніше і зрозуміліше.

Висновки: в більшості випадків numpy має перевагу над ітеративними конструкціями як у швидкості так і у простоті виконання. Але він дає менш свободи(обмеженна кількисть елементів у масива у порівнянні з листом, неможливість зберігти змінні різних типів), тому краще вміти користуватись обома засобами.

Розв’язати систему за допомогою формул Крамера і виконати перевірку за
допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose()


$$
\left\{
    \begin{array}\\
        \mbox 2X_1 - 6X_2 + 2X_3 + 2X_4 = 12\\
        \mbox 1X_1 - 3X_2 + 5X_3 + 7X_4 = 12\\
        \mbox 3X_1 - 5X_2 + 7X_3 + X_4 = 0\\
        \mbox 5X_1 - 7X_2 + X_3 + 3X_4 = 4\\
    \end{array}
\right.
$$

$$
\Delta = 
\begin{vmatrix}
2 & -6 & 2 & 2\\
1 & 3 & 5 & 7\\
3 & 5 & 7 & 1\\
5 & 7 & 1 & 3\\
\end{vmatrix} = -2048
$$

$$
\Delta_1 = 
\begin{vmatrix}
12 & -6 & 2 & 2\\
12 & 3 & 5 & 7\\
0 & 5 & 7 & 1\\
4 & 7 & 1 & 3\\
\end{vmatrix} = -2048
$$

$$
\Delta_2 = 
\begin{vmatrix}
2 & 12 & 2 & 2\\
1 & 12 & 5 & 7\\
3 & 0 & 7 & 1\\
5 & 4 & 1 & 3\\
\end{vmatrix} = 2048
$$

$$
\Delta_3 = 
\begin{vmatrix}
2 & -6 & 12 & 2\\
1 & 3 & 12 & 7\\
3 & 5 & 0 & 1\\
5 & 7 & 4 & 3\\
\end{vmatrix} = 0
$$

$$
\Delta_4 = 
\begin{vmatrix}
2 & -6 & 2 & 12\\
1 & 3 & 5 & 12\\
3 & 5 & 7 & 0\\
5 & 7 & 1 & 4\\
\end{vmatrix} = -4096
$$

$$
X_1 = \frac {\Delta_1}{\Delta} = \frac {-2048}{-2048} = 1
$$

$$
X_2 = \frac {\Delta_2}{\Delta} = \frac {2048}{-2048} = -1
$$

$$
X_3 = \frac {\Delta_3}{\Delta} = \frac {0}{-2048} = 0
$$

$$
X_4 = \frac {\Delta_4}{\Delta} = \frac {-4096}{-2048} = 2
$$

Перевірка матричним множенням:

In [8]:
import numpy as np
import fractions as fr


def matrix_minor(arr, i, j):
    return np.delete(np.delete(arr, i, axis=0), j, axis=1)


def det_mat(m1):
    if len(m1) != len(m1[0]):
        return "Determinant can only be found in square matrix."
    elif len(m1) == 2:
        return m1[0][0] * m1[1][1] - m1[0][1] * m1[1][0]
    elif len(m1) == 3:
        a = m1[0][0] * (m1[1][1] * m1[2][2] - m1[2][1] * m1[1][2])
        b = m1[0][1] * (m1[1][0] * m1[2][2] - m1[2][0] * m1[1][2])
        c = m1[0][2] * (m1[1][0] * m1[2][1] - m1[2][0] * m1[1][1])
        return a - b + c
    elif len(m1) == 4:
        a1 = m1[0][0] * (m1[1][1] * (m1[2][2] * m1[3][3] - m1[3][2] * m1[2][3]) - m1[1][2] * (
                m1[2][1] * m1[3][3] - m1[3][1] * m1[2][3]) + m1[1][3] * (m1[2][1] * m1[3][2] - m1[3][1] * m1[2][2]))
        a2 = m1[0][1] * (m1[1][0] * (m1[2][2] * m1[3][3] - m1[3][2] * m1[2][3]) - m1[1][2] * (
                m1[2][0] * m1[3][3] - m1[3][0] * m1[2][3]) + m1[1][3] * (m1[2][0] * m1[3][2] - m1[3][0] * m1[2][2]))
        a3 = m1[0][2] * (m1[1][0] * (m1[2][1] * m1[3][3] - m1[3][1] * m1[2][3]) - m1[1][1] * (
                m1[2][0] * m1[3][3] - m1[3][0] * m1[2][3]) + m1[1][3] * (m1[2][0] * m1[3][1] - m1[3][0] * m1[2][1]))
        a4 = m1[0][3] * (m1[1][0] * (m1[2][1] * m1[3][2] - m1[3][1] * m1[2][2]) - m1[1][1] * (
                m1[2][0] * m1[3][2] - m1[3][0] * m1[2][2]) + m1[1][2] * (m1[2][0] * m1[3][1] - m1[3][0] * m1[2][1]))
        return a1 - a2 + a3 - a4


A = [[2, -6, 2, 2], [1, 3, 5, 7], [3, 5, 7, 1], [5, 7, 1, 3]]
B = [[12], [12], [0], [4]]
C = np.copy(A)
det_A = det_mat(A)  # A-matrix determinant. It is non-zero that means inverse of a matrix exists.
for i in range(0, len(A)):
    for n in range(0, len(A[0])):
        C[i][n] = det_mat(matrix_minor(A, i, n)) * ((-1) ** (i + n))
C = C.transpose()  # Transposing the matrix of minor determinants
reverse = []
for i in range(0, len(A)):  # Inverse of transposed matrix
    for n in range(0, len(A[0])):
        reverse.append(fr.Fraction(numerator=C[i][n], denominator=det_A))
reverse = np.reshape(reverse, (len(A), len(A[0])))
final = np.matmul(reverse, B)
for i in range(0, len(final)):
    print(f'X{i+1} = {int(final[i])}')


X1 = 1
X2 = -1
X3 = 0
X4 = 2


Перевірка за допомогою функції оберненої матриці в numpy

In [10]:
import numpy as np


A = [[2, -6, 2, 2], [1, 3, 5, 7], [3, 5, 7, 1], [5, 7, 1, 3]]
B = [[12], [12], [0], [4]]
reverse = np.linalg.inv(A)
final = np.matmul(reverse, B)
for i in range(0, len(final)):
    print(f'X{i+1} = {int(final[i])}')



X1 = 1
X2 = -1
X3 = 0
X4 = 2


Перевірка за допомогою numpy.linalg.solve()

In [11]:
import numpy as np


A = [[2, -6, 2, 2], [1, 3, 5, 7], [3, 5, 7, 1], [5, 7, 1, 3]]
B = [[12], [12], [0], [4]]
final = np.linalg.solve(A, B)
for i in range(0, len(final)):
    print(f'X{i+1} = {int(final[i])}')



X1 = 1
X2 = -1
X3 = 0
X4 = 2


Порівняння відповідей

In [14]:
import numpy as np
import fractions as fr


def matrix_minor(arr, i, j):
    return np.delete(np.delete(arr, i, axis=0), j, axis=1)


def det_matrix(m1):
    if len(m1) != len(m1[0]):
        return "Determinant can only be found in square matrix."
    elif len(m1) == 2:
        return m1[0][0] * m1[1][1] - m1[0][1] * m1[1][0]
    elif len(m1) == 3:
        a = m1[0][0] * (m1[1][1] * m1[2][2] - m1[2][1] * m1[1][2])
        b = m1[0][1] * (m1[1][0] * m1[2][2] - m1[2][0] * m1[1][2])
        c = m1[0][2] * (m1[1][0] * m1[2][1] - m1[2][0] * m1[1][1])
        return a - b + c
    elif len(m1) == 4:
        a1 = m1[0][0] * (m1[1][1] * (m1[2][2] * m1[3][3] - m1[3][2] * m1[2][3]) - m1[1][2] * (
                m1[2][1] * m1[3][3] - m1[3][1] * m1[2][3]) + m1[1][3] * (m1[2][1] * m1[3][2] - m1[3][1] * m1[2][2]))
        a2 = m1[0][1] * (m1[1][0] * (m1[2][2] * m1[3][3] - m1[3][2] * m1[2][3]) - m1[1][2] * (
                m1[2][0] * m1[3][3] - m1[3][0] * m1[2][3]) + m1[1][3] * (m1[2][0] * m1[3][2] - m1[3][0] * m1[2][2]))
        a3 = m1[0][2] * (m1[1][0] * (m1[2][1] * m1[3][3] - m1[3][1] * m1[2][3]) - m1[1][1] * (
                m1[2][0] * m1[3][3] - m1[3][0] * m1[2][3]) + m1[1][3] * (m1[2][0] * m1[3][1] - m1[3][0] * m1[2][1]))
        a4 = m1[0][3] * (m1[1][0] * (m1[2][1] * m1[3][2] - m1[3][1] * m1[2][2]) - m1[1][1] * (
                m1[2][0] * m1[3][2] - m1[3][0] * m1[2][2]) + m1[1][2] * (m1[2][0] * m1[3][1] - m1[3][0] * m1[2][1]))
        return a1 - a2 + a3 - a4


def variant_a():
    A = [[2, -6, 2, 2], [1, 3, 5, 7], [3, 5, 7, 1], [5, 7, 1, 3]]
    B = [[12], [12], [0], [4]]
    C = np.copy(A)
    det_A = det_matrix(A)  # A-matrix determinant. It is non-zero that means inverse of a matrix exists.
    for i in range(0, len(A)):
        for n in range(0, len(A[0])):
            C[i][n] = det_matrix(matrix_minor(A, i, n)) * ((-1) ** (i + n))
    C = C.transpose()  # Transposing the matrix of minor determinants
    reverse = []
    for i in range(0, len(A)):  # Inverse of transposed matrix
        for n in range(0, len(A[0])):
            reverse.append(fr.Fraction(numerator=C[i][n], denominator=det_A))
    reverse = np.reshape(reverse, (len(A), len(A[0])))
    final = np.matmul(reverse, B)
    intfinal = np.zeros(len(final), dtype=int)
    for i in range (0, len(final)):
        intfinal[i] = int(final[i])
    return intfinal


def variant_b():
    A = [[2, -6, 2, 2], [1, 3, 5, 7], [3, 5, 7, 1], [5, 7, 1, 3]]
    B = [[12], [12], [0], [4]]
    reverse = np.linalg.inv(A)
    final = np.matmul(reverse, B)
    intfinal = np.zeros(len(final), dtype=int)
    for i in range(0, len(final)):
        intfinal[i] = int(final[i])
    return intfinal


def variant_c():
    A = [[2, -6, 2, 2], [1, 3, 5, 7], [3, 5, 7, 1], [5, 7, 1, 3]]
    B = [[12], [12], [0], [4]]
    final = np.linalg.solve(A, B)
    intfinal = np.zeros(len(final), dtype=int)
    for i in range(0, len(final)):
        intfinal[i] = int(final[i])
    return intfinal


A = variant_a()
B = variant_b()
C = variant_c()
print(np.allclose(A, B) and np.allclose(B, C))
#We can't use allclose for 3 values so we use basic logic instead
#if A = B and B = C that means A = B = C. 

True


Всі відповіді співпали.

3. Обчислити значення матричного виразу

Ітеративними конструкціями

In [14]:
import numpy as np
import time


def matrix_mul(m1, m2):
    m3 = np.zeros([len(m1), len(m1[0])], dtype=int)
    if len(m1) != len(m2) and len(m1) != len(m2):
        return "You can multiply only same sized matrices."
    for i in range(len(m1)):
        for n in range(len(m1[0])):
            for m in range(len(m1)):
                m3[i][n] += m1[i][m]*m2[m][n]
    return m3


def matrix_sum(m1, m2):
    m3 = np.copy(m1)
    if len(m1) != len(m2) and len(m1) != len(m2):
        return "You can add only same sized matrices."
    for i in range(len(m1)):
        for n in range(len(m1[0])):
            m3[i][n] += m2[i][n]
    return m3


start = time.time()
A = np.array([[2, 1, 3], [1, -2, 0], [4, -3, 0]])
B = np.array([[22, -14, 3], [6, -7, 0], [11, 3, 15]])
AplusB = matrix_sum(A, B)
AonB = matrix_mul(A, B)
Aminus = np.copy(A)
for i in range(len(Aminus)):
    for n in range(len(Aminus[0])):
        Aminus[i][n] *= -2
result = matrix_sum(AonB, Aminus)
result = matrix_mul(AplusB, result)
for i in range(len(result)):
    for n in range(len(result[0])):
        result[i][n] *= 3
print(result)
end = time.time()
print(f"It took {end - start} seconds")


[[ 6492 -2694  3339]
 [ 1443  -696   864]
 [ 6345 -2565  2565]]
It took 0.0006279945373535156 seconds


За допомогою функцій numpy

In [16]:
import numpy as np
import time

start = time.time()
A = np.array([[2, 1, 3], [1, -2, 0], [4, -3, 0]])
B = np.array([[22, -14, 3], [6, -7, 0], [11, 3, 15]])
AplusB = np.add(A, B)
AonB = np.matmul(A, B)
Aminus = A*-2
result = np.add(AonB, Aminus)
result = np.matmul(AplusB, result)
result *= 3
print(result)
end = time.time()
print(f"It took {end - start} seconds")


[[ 6492 -2694  3339]
 [ 1443  -696   864]
 [ 6345 -2565  2565]]
It took 0.0 seconds


Різниця незначна, але варіант через функції numpy в середньому швидше.

Порівняння результатів

In [21]:
import numpy as np


def matrix_mul(m1, m2):
    m3 = np.zeros([len(m1), len(m1[0])], dtype=int)
    if len(m1) != len(m2) and len(m1) != len(m2):
        return "You can multiply only same sized matrices."
    for i in range(len(m1)):
        for n in range(len(m1[0])):
            for m in range(len(m1)):
                m3[i][n] += m1[i][m] * m2[m][n]
    return m3


def matrix_sum(m1, m2):
    m3 = np.copy(m1)
    if len(m1) != len(m2) and len(m1) != len(m2):
        return "You can add only same sized matrices."
    for i in range(len(m1)):
        for n in range(len(m1[0])):
            m3[i][n] += m2[i][n]
    return m3


def variant_1():
    A = np.array([[2, 1, 3], [1, -2, 0], [4, -3, 0]])
    B = np.array([[22, -14, 3], [6, -7, 0], [11, 3, 15]])
    AplusB = matrix_sum(A, B)
    AonB = matrix_mul(A, B)
    Aminus = np.copy(A)
    for i in range(len(Aminus)):
        for n in range(len(Aminus[0])):
            Aminus[i][n] *= -2
    result = matrix_sum(AonB, Aminus)
    result = matrix_mul(AplusB, result)
    for i in range(len(result)):
        for n in range(len(result[0])):
            result[i][n] *= 3
    return result


def variant_2():
    A = np.array([[2, 1, 3], [1, -2, 0], [4, -3, 0]])
    B = np.array([[22, -14, 3], [6, -7, 0], [11, 3, 15]])
    AplusB = np.add(A, B)
    AonB = np.matmul(A, B)
    Aminus = A * -2
    result = np.add(AonB, Aminus)
    result = np.matmul(AplusB, result)
    result *= 3
    return result


A = variant_1()
B = variant_2()
print(np.allclose(A, B))


True


Відповіді співпали